//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTF_Printer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTF_Printer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap gtf_logo {
            get {
                object obj = ResourceManager.GetObject("gtf_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jpn_logo {
            get {
                object obj = ResourceManager.GetObject("jpn_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   -- END --과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringEndMark {
            get {
                return ResourceManager.GetString("StringEndMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効でない日付形式です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringErrLandingDate {
            get {
                return ResourceManager.GetString("StringErrLandingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GOODS DETAILS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails {
            get {
                return ResourceManager.GetString("StringGoodsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入年月日과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails01 {
            get {
                return ResourceManager.GetString("StringGoodsDetails01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消耗品과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails02 {
            get {
                return ResourceManager.GetString("StringGoodsDetails02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一般物品과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails03 {
            get {
                return ResourceManager.GetString("StringGoodsDetails03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails04 {
            get {
                return ResourceManager.GetString("StringGoodsDetails04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単価과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails05 {
            get {
                return ResourceManager.GetString("StringGoodsDetails05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails06 {
            get {
                return ResourceManager.GetString("StringGoodsDetails06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   販売価格과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails07 {
            get {
                return ResourceManager.GetString("StringGoodsDetails07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   免税額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails08 {
            get {
                return ResourceManager.GetString("StringGoodsDetails08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合計価額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails09 {
            get {
                return ResourceManager.GetString("StringGoodsDetails09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返金額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails10 {
            get {
                return ResourceManager.GetString("StringGoodsDetails10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総合計価額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails11 {
            get {
                return ResourceManager.GetString("StringGoodsDetails11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総返金額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails12 {
            get {
                return ResourceManager.GetString("StringGoodsDetails12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総手数料과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails13 {
            get {
                return ResourceManager.GetString("StringGoodsDetails13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総免税額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails14 {
            get {
                return ResourceManager.GetString("StringGoodsDetails14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全店合計消耗品販売額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails15 {
            get {
                return ResourceManager.GetString("StringGoodsDetails15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全店合計一般物品販売額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails16 {
            get {
                return ResourceManager.GetString("StringGoodsDetails16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ---------------------------------------------------------------과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringLine {
            get {
                return ResourceManager.GetString("StringLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運営会社과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringOperationName {
            get {
                return ResourceManager.GetString("StringOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   旅券과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringPassPortEtc01 {
            get {
                return ResourceManager.GetString("StringPassPortEtc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外交官과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringPassPortEtc02 {
            get {
                return ResourceManager.GetString("StringPassPortEtc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   乗組員上陸許可書과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringPassPortEtc03 {
            get {
                return ResourceManager.GetString("StringPassPortEtc03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   緊急上陸許可書과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringPassPortEtc04 {
            get {
                return ResourceManager.GetString("StringPassPortEtc04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遭難上陸許可書과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringPassPortEtc05 {
            get {
                return ResourceManager.GetString("StringPassPortEtc05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unique ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRefundSerial {
            get {
                return ResourceManager.GetString("StringRefundSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REFUND DETAIL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRefundway {
            get {
                return ResourceManager.GetString("StringRefundway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   還付方法과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRefundWayDesc {
            get {
                return ResourceManager.GetString("StringRefundWayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   還付方法과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRefundWayName {
            get {
                return ResourceManager.GetString("StringRefundWayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   / QQID 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRefundWayQQ {
            get {
                return ResourceManager.GetString("StringRefundWayQQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   / UPI No. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRefundWayUPI {
            get {
                return ResourceManager.GetString("StringRefundWayUPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再発行과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRePublish {
            get {
                return ResourceManager.GetString("StringRePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RETAILER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer {
            get {
                return ResourceManager.GetString("StringRetailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所轄税務署과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer01 {
            get {
                return ResourceManager.GetString("StringRetailer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納税地과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer02 {
            get {
                return ResourceManager.GetString("StringRetailer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   販売者氏名・名称과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer03 {
            get {
                return ResourceManager.GetString("StringRetailer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   販売場所在地과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer04 {
            get {
                return ResourceManager.GetString("StringRetailer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票番号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipNo {
            get {
                return ResourceManager.GetString("StringSlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出免税物品購入記録票과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01 {
            get {
                return ResourceManager.GetString("StringSlipType01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスポート添付用과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01AddText01 {
            get {
                return ResourceManager.GetString("StringSlipType01AddText01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ① 本邦から出国する際又は居住者となる際に、その出港地を所轄する税関長又はその住所若しくは居所の所在地を所轄する税務署長に購入記録票を提出しなければなりません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc01 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ② 本邦から出国するまでは購入記録票を旅券等から切り離してはいけません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc02 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ③ 免税で購入した物品を本邦からの出国の際に所持していなかった場合には、その購入した物品について免除された消費税額（地方消費税を含む。）に相当する額を徴収されます。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc03 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ④ ③の場合において、災害その他やむを得ない事情により免税で購入した物品を亡失したため輸出しないことにつき税関長の承認を受けたとき、又は既に輸出したことを証する書類を出港地を所轄する税関長に提出したときは、消費税額（地方消費税を含む。）に相当する額を徴収されません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc04 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終的に輸出となる物品の
        ///消費税免税購入についての購入者誓約書과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02 {
            get {
                return ResourceManager.GetString("StringSlipType02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗控用과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02AddText01 {
            get {
                return ResourceManager.GetString("StringSlipType02AddText01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   当該消耗品を、購入した日から３０日以内に輸出されるものとして購入し、日本で処分しないことを誓約します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02Desc01 {
            get {
                return ResourceManager.GetString("StringSlipType02Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   当該一般物品を、日本から最終的には輸出されるものとして購入し、日本で処分しないことを誓約します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02Desc02 {
            get {
                return ResourceManager.GetString("StringSlipType02Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   署名　Signature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02Signature {
            get {
                return ResourceManager.GetString("StringSlipType02Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出免税物品購入記録票(控え)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType03 {
            get {
                return ResourceManager.GetString("StringSlipType03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者控え과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType04 {
            get {
                return ResourceManager.GetString("StringSlipType04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出免税物品販売者控え과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType05 {
            get {
                return ResourceManager.GetString("StringSlipType05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合算発行伝票과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType06 {
            get {
                return ResourceManager.GetString("StringSlipType06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合算伝票番号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType06No {
            get {
                return ResourceManager.GetString("StringSlipType06No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TOURIST&apos;S DETAILS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails {
            get {
                return ResourceManager.GetString("StringTouristDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   旅券等の種類과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails01 {
            get {
                return ResourceManager.GetString("StringTouristDetails01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails02 {
            get {
                return ResourceManager.GetString("StringTouristDetails02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者氏名과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails03 {
            get {
                return ResourceManager.GetString("StringTouristDetails03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   国籍과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails04 {
            get {
                return ResourceManager.GetString("StringTouristDetails04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生年月日과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails05 {
            get {
                return ResourceManager.GetString("StringTouristDetails05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在留資格과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails06 {
            get {
                return ResourceManager.GetString("StringTouristDetails06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上陸地과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails07 {
            get {
                return ResourceManager.GetString("StringTouristDetails07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上陸年月日과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails08 {
            get {
                return ResourceManager.GetString("StringTouristDetails08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButton_Close_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButton_Close.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButton_Print_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButton_Print.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
